version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
  android: circleci/android@2.1.2

jobs:
  build-ui-test:
    executor:
      name: android/android-machine
      tag: 2023.05.1
      resource-class: large
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - android/create-avd:
          avd-name: testDevice
          system-image: system-images;android-30;google_apis;x86
          install: true
      - android/start-emulator:
          avd-name: testDevice
          no-window: true
          restore-gradle-cache-prefix: v1a
          post-emulator-launch-assemble-command: echo "Emulator Started"
      - android/run-tests:
          test-command: ./gradlew testing:jacocoTestReport
          max-tries: 5
      - store_test_results:
          path: testing/build/outputs/androidTest-results
      - android/save-gradle-cache:
          cache-prefix: v1a
  build-test-sonar:
    executor:
      name: android/android-machine
      tag: 2023.05.1
      resource-class: large
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Set Up
          command: | 
            ./gradlew wrapper 
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Run Tests
          command: |
            ./gradlew lib:testDebugUnitTest 
            ./gradlew lib:jacocoTestReport
      - run:
          name: Upload Coverage Report to SonarCloud
          command: ./gradlew sonarqube
      - store_test_results:
          path: lib/build/test-results/testDebugUnitTest
  deploy-to-sonatype:
    docker:
      - image: cimg/android:2023.05-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Set Up
          command: |
            ./gradlew wrapper
            ./gradlew lib:androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Inject Maven signing key
          command: |
            chmod +x signing.sh
            ./signing.sh
      - run:
          name: Publish to Maven
          command: ./gradlew lib:assemble publish
workflows:
  build-test-sonar-publish:
    jobs:
      - build-ui-test:
          context:
            - mobile
      - build-test-sonar:
          context:
            - SonarCloud
            - mobile
      - deploy-to-sonatype:
          name: Build, run tests, sonar and push to maven staging
          context:
            - maven-sign
            - mobile
          requires:
            - build-test-sonar
            - build-ui-test
          filters:
            branches:
              only:
                - staging